### ISSUE TITLE
To build the javascript version do I need Linux or can I do it on Windows?

### ISSUE THREAD

**Issue by lexterror** [Stellarium/stellarium-web-engine#10]
Is there detailed instructions on building this?

Thank you

**Comment by xalioth** [comment]
Hi,

you currently need a linux to build it. I personnally use Ubuntu 18.04. It should be possible to have this working on windows as well, if you have a working version of make (maybe nmake?) and build inside docker.

The doc is there: https://github.com/Stellarium/stellarium-web-engine/blob/stellarium-web/web-frontend/README.md

Feel free to give a try, contributions are welcome!

Fabien
