### ISSUE TITLE
IT seems that stellarium web give Swan Nebula when searching Omega Cluster.

### ISSUE THREAD

**Issue by zoomx** [Stellarium/stellarium-web-engine#101]
### Expected Behaviour
showing position of Omega Cluster

### Actual Behaviour
Show position of Swan Nebula

### Steps to reproduce
Go to stellarium web
Search for Omega Cluster and select

![WhatsApp Image 2021-07-20 at 10 28 04](https://user-images.githubusercontent.com/3438818/126290599-d11254a4-d85f-403b-82c5-90986a0b766f.jpeg)
Left up says Omega Nebula, Open Cluster but the description is of Swan Nebula

**Comment by gzotti** [comment]
Omega nebula is a well known alternative for the Swan nebula. 
What is the Omega cluster?

**Comment by zoomx** [comment]
Omega Centauri, ω Cen, NGC 5139

**Comment by gzotti** [comment]
Then search for Omega Centauri...

**Comment by zoomx** [comment]
![immagine](https://user-images.githubusercontent.com/3438818/126604647-6db03bc3-2a6b-43df-8e11-643208c17363.png)
Searching for Omega you get only the Omega nebula and it's written that it is an open cluster. Instead it is the nebula and not the cluster. There is not other findings, only this one. I think that open cluster should be changed in nebula.

If you search for NGC 5139 you find Omega Centauri.

**Comment by gzotti** [comment]
While typing "om" the second hit is omega Centauri. The "Omega Nebula" just is M17, also called Swan Nebula, an open cluster nested in emission nebula. 

The term "omega cluster" does not exist anywhere.

It seems the abbreviated search term for the Greek letter omega is "ome". Enter "ome " (with space) and see all notable "omega" entries.
