### ISSUE TITLE
Location of the Input data for drawing the constellation pattern.

### ISSUE THREAD

**Issue by martinmestre** [Stellarium/stellarium-web-engine#105]
Hello!
I would like to know where is located the input file with the constallations data. 
I guess it is a two table column with the stars IDs that contribute with a given segment of a given constellation pattern?
Thank you very much in advance.
Martín

**Comment by xalioth** [comment]
Hi,

it's in this subproject: https://github.com/Stellarium/stellarium-skycultures

Fabien
