### ISSUE TITLE
Accuracy of satellite positions

### ISSUE THREAD

**Issue by rtphokie** [Stellarium/stellarium-web-engine#106]
Based on the behavior and [JSON file downloaded](https://api.noctuasky.com/api/v1/skysources/name/NORAD%2025544) that Stellarium-Web is using nearly week old TLEs, which, at least in the case of the ISS and probably other artificial satellites, is causing rise/set times to be off by several minutes.

Looking at the above link, the TLE downloaded on 2021-08-22T1800Z is

1 25544U 98067A   21231.85950031  .00001072  00000-0  27662-4 0  9997
2 25544  51.6440  27.8463 0001517 333.1303 175.6838 15.48918110298467

Which has an epoch of 2021-08-19T20:37:40Z

The most recent has an epoch of 2021-08-22T11:57:41 and produces much more accurate positions.

Can the data being served by the API be updated more frequently, daily would be appropriate.  Or perhaps have the end user fetch directly from [Celestrak](http://celestrak.com/NORAD/elements/stations.txt) where available.

**Comment by xalioth** [comment]
Hi,

you are right, there is a quite long delay for the TLE data returned from the API. It's caused by various CRON scripts starting at different times and presumably at least one caching issue. However at the moment the engine in stellarium-web is not using this data but a file copied from celestrak directly.

**Comment by rtphokie** [comment]
Just verified a specific ISS against Stellarium desktop, [Heavens Above](https://www.heavens-above.com/passdetails.aspx?&satid=25544&mjd=59450.4864656961&type=V&lat=34.2018&lng=-118.1729) and a Python script levering the SkyField package.  All appear to be within a few seconds and half a degree.  So yeah

For example:
location 34º11'58" N, 118º10'11" W
date: 2021-08-24, exist shadow at 04:40:37 AM local (PDT)
