### ISSUE TITLE
Can’t find license

### ISSUE THREAD

**Issue by jbergen** [Stellarium/stellarium-web-engine#107]
Great project and I'm looking forward to using it! However I'd love some clarification on the software license type to better understand exactly how I'm able to use it. Perhaps the license does exist in the repo end I missed it? Thank you in advance

**Comment by xalioth** [comment]
Hello, the license is dual AGPL v3 / commercial

The main AGPL v3 license file was still in the web-frontend/ directory following an old refactoring. I just moved it to the top directory.
