### ISSUE TITLE
How to display Chinese culture in the stellarium-web?

### ISSUE THREAD

**Issue by nicholastc2** [Stellarium/stellarium-web-engine#109]
How to display Chinese culture in the stellarium-web?
Its default setting is western culture.

**Comment by xalioth** [comment]
Hello it's not yet possible for the version currently online..

It's not much work to add them in the web version but I need to find this
time..

Fabien

Le ven. 1 oct. 2021 à 09:18, nicholastc2 ***@***.***> a
écrit :

**Comment by xalioth** [comment]
Even though it's a bit hacky, it now possible to specify a sky culture using the 'sc' parameter in the URL. For the chinese sky culture you can try this:

https://stellarium-web.org/?sc=https%3A%2F%2Fraw.githubusercontent.com%2FStellarium%2Fstellarium-skycultures%2Fmaster%2Fchinese
