### ISSUE TITLE
Stars are not visible in PC browser

### ISSUE THREAD

**Issue by Regulus-mj94** [Stellarium/stellarium-web-engine#111]
Hi
I can't see stars in stellarium web from my pc browsers (chrome and edge). I cleaned the chrome cache and cookies but see no diffrence. I don't have this issue in android phone.
![Screenshot 2021-10-08 1531292](https://user-images.githubusercontent.com/84971633/136561144-657785e2-c491-432f-862a-e36df1a6c258.jpg)

**Comment by Regulus-mj94** [comment]
I tried on firefox but still stars are not visible.
Probably an issue on my side, but how can I find the reason?

**Comment by xalioth** [comment]
Thanks I don't see anything related to a graphic card issue in the logs.. As very few people complain about that, I really tend to think it's a graphic card/driver issue. Try maybe to update your drivers?

Fr the time being I'll just close this issue, please re-open if you get new data!
