### ISSUE TITLE
DSO images not showing locally

### ISSUE THREAD

**Issue by swaterfall** [Stellarium/stellarium-web-engine#117]
Hey,

I'm playing around with a local build but the DSO images don't appear:

**Local:**
<img width="607" alt="Screenshot 2021-11-05 at 18 51 28" src="https://user-images.githubusercontent.com/541538/140563599-eaca2a5f-cd62-4cac-9b51-b40790808afb.png">

**Stellarium-web.org:**
<img width="623" alt="Screenshot 2021-11-05 at 18 52 06" src="https://user-images.githubusercontent.com/541538/140563631-8a9641a9-d32b-48d7-a70e-185609c9e0dc.png">

What do I need to do to get this working?

Thanks

**Comment by xalioth** [comment]
Hi,

it's because only stellarium-web.org can access these images, we don't want to open this imaging server for legal licensing reasons, and also for server cost reasons.

Let me know

**Comment by swaterfall** [comment]
Makes sense.

Are there functions for adding image layers using JS? If not what would be the best way to get something similar working? Seems like a lot of people are using DSS/Aladin Sky Atlas.
