### ISSUE TITLE
When building the JS version does it include all dependencies?

### ISSUE THREAD

**Issue by lexterror** [Stellarium/stellarium-web-engine#12]
I wanted to know if after building the JS version on Linux it would include all dependencies like graphics, stars data, etc.. 

Thank you!

**Comment by xalioth** [comment]
No, it will include the engine and basic graphics assets such as icons etc..

Most of the data is hosted on our external servers, as it's a very large mount of data. There are also a couple of web services, for location lookup and object search which are hosted on another web server. By default, your locals build will use these services.

Fabien
