### ISSUE TITLE
Touchpad tap will not select stars; an actual button click does

### ISSUE THREAD

**Issue by tupelo-schneck** [Stellarium/stellarium-web-engine#122]
I have my laptop touchpads configured with "tap to click".  Nonetheless, in Stellarium Web, tapping does not select stars.  Actually clicking does.

Observed on Google Chrome, on both Windows and Mac.

**Comment by wimulkeman** [comment]
@tupelo-schneck Are you still encountering this issue? If so could you provide your Chrome version?

**Comment by tupelo-schneck** [comment]
I can confirm that today this is no longer a problem for me!
