### ISSUE TITLE
Questions about delta T and 1582 Calendar Reform

### ISSUE THREAD

**Issue by nicholastc2** [Stellarium/stellarium-web-engine#123]
thank you for your attention
I hope my words are not too amateur for you to understand:）
Is there a time correction function in the online version by default, especially about ΔT and 1582 Calendar Reform? 
Because I found that once I entered a date before 1582, the 3D image presented by the web version was different from the PC version.
Thanks again for you kind help~

**Comment by gzotti** [comment]
You could use the Calendars plugin in the Desktop version to show both Julian and Gregorian calendar dates, then see what calendar the web version uses. The web version is more geared towards the present time, not for historical research.

**Comment by xalioth** [comment]
Hi thanks Georg!
As you noticed, for the moment we didn't implement the calendar jump on October 4th 1582, so it's gregorian only.
