### ISSUE TITLE
Dss STELLARIUM PLUS

### ISSUE THREAD

**Issue by cork124** [Stellarium/stellarium-web-engine#132]
HOW DO I TURN OFF DSS AND TURN IT ON AGAIN

**Comment by xalioth** [comment]
In the mobile version it's not possible to switch it off at the moment.

**Comment by cork124** [comment]
Tech me how to create program of starry Sky

**Comment by JAY-Githb** [comment]
The question is much too broad. It has to be more specific as to what you want.

**Comment by gzotti** [comment]
I am afraid cork124 is some insignificant individual from Brazil who has nothing else to do than notoriously spamming us.
