### ISSUE TITLE
Questions about building web-frontend

### ISSUE THREAD

**Issue by JohnHawkinsWei** [Stellarium/stellarium-web-engine#148]
Hey guys,
I am quite noob at scripting, my english is not good though.
I have Ubuntu 18.04 with docker and all the dependencies installed. I have tried to build Stellarium-web-frontend but got these questions:

**1. how to build the app to deploy at a sub-path?**

it seems like the web-frontend is configued to be deployed at the root of a domain, e.g. https://www.XXX.com/
when i put the files into a sub-path, e.g. https://www.XXX.com/sub-path/ , it won't work.
i try to change the setting in this file: /apps/web-frontend/vue.config.js
i changed the publicPath into publicPath: './'
but when u open up index.html nothing changed.

**2. is there any way to change the UI language?**

i try to change the setting in this file: /apps/web-frontend/vue.config.js
i changed all the 'en' into other lauguage, but not working.

**3. the search function not working**
**4. share target link function not working**
when u select a target (such as a star), u can create a link with location and time params, but it refers to the stellarium-web.org domain.

i found that the built version have the different dir structure from the stellarium-web.org version
is the web-frontend version i built exactly same as which deployed at stellarium-web.org?
am i miss something or the server needs some other dependencies to install?

How to fix this?
Thanks a lot!

**Comment by xalioth** [comment]
Hi John,

for 1., I never tried to change to a sub-path, so I guess you should try by yourself, the settings are a bit spread in the vue-cli config indeed. A patch is welcome if you manage to do that in a flexible way.

For 2., no, I started working on this but never had time to complete this task. The code is half-baked at the moment, so like for 1. I guess some help is needed here.

For 3., the search function is making use of our web service, which is not open source, so you probably need to re-code one yourself.

For 4., it's probably quite easy to fix that, feel free to have a try. I am too busy with other tasks at the moment to spend time on this, at least during the next months.

Best

**Comment by JohnHawkinsWei** [comment]
thank u so much, it helps a lot ;D
