### ISSUE TITLE
[SConstruct] ValueError : unsupported pickle protocol: 4

### ISSUE THREAD

**Issue by luk0y** [Stellarium/stellarium-web-engine#168]
Okay. This one is fixed.

Issue coming when I directly run `sudo make setup`

After using `sudo -i` and running `make setup`, That issue got sorted out

_Originally posted by @luk0y in https://github.com/Stellarium/stellarium-web-engine/issues/166#issuecomment-1343787052_

Now I am getting and there were no temporary python files in web-frontend folder

```
scons: *** [SConstruct] ValueError : unsupported pickle protocol: 4
scons: building terminated because of errors.
make: *** [Makefile:18: js-es6] Error 2
make[2]: *** [Makefile:12: gen-es6] Error 2
make[2]: Leaving directory '/home/<path>/stellarium-web-engine-master/apps/web-frontend'
make[1]: *** [Makefile:21: update-engine] Error 2
make[1]: Leaving directory '/home/<path>/stellarium-web-engine-master/apps/web-frontend'
make: *** [Makefile:38: setup] Error 2
```

**Comment by luk0y** [comment]
Solved this issue by deleting .db file(Seems like it belongs to conscript) inside stellarium-web-engine-master and then rerunning `make setup`

**Comment by FEXAQAQ** [comment]
> 透過刪除 stellarium-web-engine-master 中的 db 檔案（似乎屬於 conscript）然後重新運行解決了這個問題`make setup`。檔案名稱以.（點）開頭，因此輸入ctrl+H即可查看stellarium-web-engine-master根目錄下的文件

Thank you very much this was very helpful to me!

**Comment by YapZanan** [comment]
hello, i have the same problem but the .db file are not present, can you tell me where is the db file located @FEXAQAQ?

**Comment by FEXAQAQ** [comment]
> 你好，我有同樣的問題，但 .db 檔案不存在，可以告訴我 db 檔案位於哪裡嗎@FEXAQAQ？

Hi YapZanan, 
I have the impression that ".sconsign.dblite" is a hidden file. This file is located in the project root directory, which is the same layer as where you issued the "make js" command.

my own approach is to execute "make js" first, after completion execute "rm .sconsign.dblite".

finally, I hope it helps you, and I wish you all the best!

**Comment by YapZanan** [comment]
> > 你好，我有同樣的問題，但 .db 檔案不存在，可以告訴我 db 檔案位於哪裡嗎@FEXAQAQ？
> 
> Hi YapZanan, I have the impression that ".sconsign.dblite" is a hidden file. This file is located in the project root directory, which is the same layer as where you issued the "make js" command.
> 
> my own approach is to execute "make js" first, after completion execute "rm .sconsign.dblite".
> 
> finally, I hope it helps you, and I wish you all the best!

Thank you for your answer, FEXAQAQ! It is now working. I followed your suggestion and it resolved the issue. I appreciate your help!
