### ISSUE TITLE
Lucy in the Sky with... rectangles?

### ISSUE THREAD

**Issue by shackdn** [Stellarium/stellarium-web-engine#183]
Hi fantastic software, I really appreciate it.
I was just curious why there was a large rectangle covering a Sagittarius star near Omicron/Pi Sagittarii?
Star name
gaia dr2 4082081263379304448
https://stellarium-web.org/skysource/TYC6295-659-1?fov=20.719&date=2023-06-06T16:02:17Z&lat=-27.49&lng=153.08&elev=0
Cheers
David

![stellarium-webDOTorg web based sky view star observatory - github bug report for gaia dr2 4082081263379304448](https://github.com/Stellarium/stellarium-web-engine/assets/135724259/194820e5-4b9b-442f-95d7-2017fa5a6341)

**Comment by gzotti** [comment]
This covers up the alien starships...

**Comment by gzotti** [comment]
Seriously: we did not create the images. They come from scientific surveys and have their own little problems. There may be the occasional image error as seen here.

**Comment by shackdn** [comment]
> This covers up the alien starships...

ahh so I've accidentally stumbled across LGM-2 =)
https://en.wikipedia.org/wiki/PSR_B1919%2B21#Discovery

Thankyou for that laugh - needed that, and best response to a bug report EVER! =)

**Comment by gzotti** [comment]
While I don't work on this repo directly, it's safe to assume "won't fix".
