### ISSUE TITLE
Permission to use Stellarium web engine in my project

### ISSUE THREAD

**Issue by wykhuh** [Stellarium/stellarium-web-engine#186]
I’m a software developer interested in using Stellarium web engine in a project. I own a Dwarf II smart telescope https://dwarflab.com/products/dwarf-2-smart-telescope. Dwarf II has an API that let people control the scope,  so I thought it would be a fun side project to build an open source app  to control the scope. I would like to include the Stellarium web engine in the app. 

The app is open source and free, and people will be able to access the site online or run it locally.  Here is the [repo](https://github.com/DwarfTelescopeUsers/dwarfii-stellarium-goto).  I don't work for Dwarf Lab, I just own their telescope. Would it be ok if use the Stellarium web engine in my app? If I have permission to use the app, what is the proper way to credit your project in the repo and in the app?

**Comment by gzotti** [comment]
I am somewhat confused. The Repo you link uses Stellarium (desktop version), which you can of course use like this. Are you asking because you want to change this repo to use stellarium-web, or add support for both?

**Comment by wykhuh** [comment]
My web app currently connects to Stellarium desktop with the remote control plugin. I want to add stellarium-web to my web app so people don't have to switch between the browser and Stellarium desktop.

**Comment by wykhuh** [comment]
I emailed the folks at Stellarium web, and Fabien said I can use Stellarium web engine for my project.

Thanks!

**Comment by gzotti** [comment]
Good!

But please keep a mode with the desktop edition, just got mine (for my club...) :-)

**Comment by wykhuh** [comment]
@gzotti I will keep the desktop edition for those who want the full functionality of Stellarium desktop. :-)

I also just started another project where people can start a tcp server in Python, and then use Stellarium  desktop Telescope Control plugin to send slew commands to the tcp server, and the tcp server can send goto messages to the Dwarf II.  I haven't tested the accuracy of the goto yet because it's been cloudy, but hopefully I can get it working when the weather is better.  https://github.com/DwarfTelescopeUsers/dwarf_tcp_server
