### ISSUE TITLE
How to fix Uncaught SyntaxError: Unexpected token ')'  on stellarium-web-engine.html

### ISSUE THREAD

**Issue by FEXAQAQ** [Stellarium/stellarium-web-engine#212]
Error Message : Uncaught SyntaxError: Unexpected token ')' (at stellarium-web-engine.html:228:12)

Step1.  Find stellarium-web-engine.html

Step2.  Find line 228 and replace the code :

```
// Force ui update when there is any change.
stel.change(function(obj, attr) {
	if (attr !== "hovered") {
		that.stel = Object.assign(Object.create(stel), {}, stel);
	} 
});
```

Step3. Reload the web page

**Comment by qaqq00** [comment]
Even more errors

**Comment by qaqq00** [comment]
> > Even more errors
> 
> Hi, the file I modified is stellarium-web-engine.html located in simple-html. Are you on the same profile?
> 
> Complete route: \apps\simple-html\stellarium-web-engine.html

Yes, but it’s alreight, ive fixed it

**Comment by qaqq00** [comment]
Thank you

**Comment by FEXAQAQ** [comment]
> > > Even more errors
> > 
> > 
> > Hi, the file I modified is stellarium-web-engine.html located in simple-html. Are you on the same profile?
> > Complete route: \apps\simple-html\stellarium-web-engine.html
> 
> Yes, but it’s alreight, ive fixed it

Congratulations! Glad you figured it out. Would you like to share how you solved it? :)

**Comment by qaqq00** [comment]
> > > > > Even more errors
> > > > 
> > > > 
> > > > Hi, the file I modified is stellarium-web-engine.html located in simple-html. Are you on the same profile?
> > > > Complete route: \apps\simple-html\stellarium-web-engine.html
> > > 
> > > 
> > > Yes, but it’s alreight, ive fixed it
> > 
> > 
> > Congratulations! Glad you figured it out. Would you like to share how you solved it? :)
> 
> Sure ` // Force ui update when there is any change.           stel.change(function(obj, attr) {             if (attr !== "hovered") {               that.stel = Object.assign(Object.create(stel), {}, stel);           }}); `

I find that it is exactly the same as what you provided orz; but i dont know why it failed at first, sorry

**Comment by FEXAQAQ** [comment]
> > > > > > Even more errors
> > > > > 
> > > > > 
> > > > > Hi, the file I modified is stellarium-web-engine.html located in simple-html. Are you on the same profile?
> > > > > Complete route: \apps\simple-html\stellarium-web-engine.html
> > > > 
> > > > 
> > > > Yes, but it’s alreight, ive fixed it
> > > 
> > > 
> > > Congratulations! Glad you figured it out. Would you like to share how you solved it? :)
> > 
> > 
> > Sure ` // Force ui update when there is any change.           stel.change(function(obj, attr) {             if (attr !== "hovered") {               that.stel = Object.assign(Object.create(stel), {}, stel);           }}); `
> 
> I find that it is exactly the same as what you provided orz; but i dont know why it failed at first, sorry

It's OK! Have a good day :D

**Comment by qaqq00** [comment]
i notice that you are also studying how the project works, may i have your email and ask some qestions about how to make setup in the web-frontend? Ive been stuck for several days qaq


---- Replied Message ----
| From | ***@***.***> |
| Date | 07/04/2024 11:06 |
| To | Stellarium/stellarium-web-engine ***@***.***> |
| Cc | qaqq00 ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [Stellarium/stellarium-web-engine] How to fix Uncaught SyntaxError: Unexpected token ')' on stellarium-web-engine.html (Issue #212) |

Even more errors

Hi, the file I modified is stellarium-web-engine.html located in simple-html. Are you on the same profile?
Complete route: \apps\simple-html\stellarium-web-engine.html

Yes, but it’s alreight, ive fixed it

Congratulations! Glad you figured it out. Would you like to share how you solved it? :)

Sure  // Force ui update when there is any change.           stel.change(function(obj, attr) {             if (attr !== "hovered") {               that.stel = Object.assign(Object.create(stel), {}, stel);           }});

I find that it is exactly the same as what you provided orz; but i dont know why it failed at first, sorry

It's OK! Have a good day :D
