### ISSUE TITLE
dependencies were not found

### ISSUE THREAD

**Issue by binoysarker** [Stellarium/stellarium-web-engine#26]
I am trying to use this web-frontend folder section with node. But i am getting this error
`These dependencies were not found:

* @/assets/js/stellarium-web-engine.js in ./src/assets/sw_helpers.js
* @/assets/js/stellarium-web-engine.wasm in ./node_modules/vuetify-loader/lib/loader.js??ref--19-0!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save @/assets/js/stellarium-web-engine.js @/assets/js/stellarium-web-engine.wasm
^C
`
Please help my with this.

**Comment by xalioth** [comment]
Hi,

I replied in #8 already.

Fabien
