### ISSUE TITLE
swe-dev:latest pull access denied

### ISSUE THREAD

**Issue by binoysarker** [Stellarium/stellarium-web-engine#27]
I am using docker to setup this and i run this command 
`sudo make setup build dev start`

But i am getting this error
`docker build -t stellarium-web-dev .
Sending build context to Docker daemon  179.3MB
Step 1/9 : FROM node:12.10.0-alpine
 ---> ef7d474eab14
Step 2/9 : EXPOSE 8080
 ---> Using cache
 ---> c35d06620b0d
Step 3/9 : EXPOSE 8888
 ---> Using cache
 ---> 06c17dcb432f
Step 4/9 : WORKDIR /app
 ---> Using cache
 ---> 2d2706d91e7e
Step 5/9 : RUN chown -R node /app
 ---> Using cache
 ---> 749a209e2861
Step 6/9 : USER node
 ---> Using cache
 ---> 88092b9fe66c
Step 7/9 : RUN id node
 ---> Using cache
 ---> 79552ac81d2d
Step 8/9 : RUN yarn
 ---> Using cache
 ---> f013345a31bb
Step 9/9 : CMD yarn run dev
 ---> Using cache
 ---> eed6cc09988d
Successfully built eed6cc09988d
Successfully tagged stellarium-web-dev:latest
docker run -it --rm -v "/home/binoy/Documents/fiverr/imborx/stellarium-web-engine-stellarium-web/web-frontend:/app" stellarium-web-dev yarn
yarn install v1.17.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > vue2-leaflet@2.2.1" has unmet peer dependency "@types/leaflet@^1.2.11".
warning " > eslint-plugin-vuetify@1.0.0-beta.3" has incorrect peer dependency "eslint@^6.0.0".
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > vuetify-loader@1.3.0" has unmet peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.21.1", while you're on "1.17.3".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
Done in 32.72s.
cd .. && make gen-es6
make[1]: Entering directory '/home/binoy/Documents/fiverr/imborx/stellarium-web-engine-stellarium-web'
docker run -it -p 8000:8000 -v "/home/binoy/Documents/fiverr/imborx/stellarium-web-engine-stellarium-web:/app" swe-dev /bin/bash -c "source /emsdk/emsdk_env.sh && make js-es6"
Unable to find image 'swe-dev:latest' locally
docker: Error response from daemon: pull access denied for swe-dev, repository does not exist or may require 'docker login'.
See 'docker run --help'.
Makefile:67: recipe for target 'gen-es6' failed
make[1]: *** [gen-es6] Error 125
make[1]: Leaving directory '/home/binoy/Documents/fiverr/imborx/stellarium-web-engine-stellarium-web'
Makefile:12: recipe for target 'update-engine' failed
make: *** [update-engine] Error 2
`
Please help me with this. Thanks.

**Comment by xalioth** [comment]
Hi,

I replied in #8 already. Basically, you need to call "make setup" once in the root directory.

Fabien
