### ISSUE TITLE
Stellarium Web

### ISSUE THREAD

**Issue by kjames11** [Stellarium/stellarium-web-engine#30]
@xalioth Currently, when the Sun is 1° above horizon, the light shaft (and shadow) is already gone. This looks not nice, e.g. when you look at the sphere in the direction of the Sun (the shadowed part): the sphere seems to start glowing for a while until the Sun goes below horizon.

With smoothstep edges of -0.026, -0.0035 instead of the current 0.02, 0.04 this looks much better but, when you look how the shadow extends into infinity, it goes into the sky: 
![image](https://user-images.githubusercontent.com/60821002/74115185-ab51f080-4b8c-11ea-84e2-dce55c79e83e.png)
I suppose this is normal, given this real-life photo (source): 
![image](https://user-images.githubusercontent.com/60821002/74115248-0257c580-4b8d-11ea-9dad-789066dab784.png) even forking files and implementing even editing files on github this procedure is done yes or no

**Comment by kjames11** [comment]
> Hi, I'm not sure what you mean. Do you have a patch for testing maybe?

precomputed atmospheric scattering evey we forking and implementing for stellarium web even editing files please fabien teach me if you have time

**Comment by kjames11** [comment]
how add clouds on stellarium web and also how implement a new atmosphere even editing and creating files for stellarium web

**Comment by kjames11** [comment]
i m say it

**Comment by kjames11** [comment]
even editing files i can fork and implement the new moidel of atmosphere for stellarium web  when you editing files the atmosphere change explain me you understood fabien i also understand teach me how to fork and implement on github i not know how fork and implement on github okay fabien i have files to you analyze when we observe the atmosphere the shaded part the sphere seems to start glowing for a while until the Sun goes below horizon. help me fabien

**Comment by kjames11** [comment]
you can try with the files for stellarium web okay fabien http://www.keckobservatory.org/videos/cosmic/19/08/19/keckccam.mp4

**Comment by kjames11** [comment]
> Oi, não sei o que você quer dizer. Você tem um patch para testar, talvez?

what i was saying to you is how fork and implement a atmosphere even editing files of stellarium web engine you can teach me how implement and add resources for stellarium won github okay

**Comment by kjames11** [comment]
https://github.com/ebruneton/precomputed_atmospheric_scattering you can how fork and implement on github the atmosphere for stellarium web okay fabien you will reply my asks

**Comment by kjames11** [comment]
you can see the comparison https://www.youtube.com/watch?v=AsBlW9WGXMA

**Comment by kjames11** [comment]
i m need of help with stellarium web 
![image](https://user-images.githubusercontent.com/60821002/74875590-4727ed00-5341-11ea-8150-d8f179fce467.png) i do not like of animation you understand fabien here it is the image of belt of venus and shadow earth the new model of atmosphere that i want http://www.keckobservatory.org/videos/cosmic/19/06/11/keckccam.mp4 you can also a implementation of atmosphere on github thanks fabien

**Comment by kjames11** [comment]
@xalioth you can implement a new model of atmosphere on stellarium web https://youtu.be/io97HJt02cY

**Comment by kjames11** [comment]
the new model of atmosphere is real i want @10110111

**Comment by kjames11** [comment]
the atmosphere is not real i want a new model of atmosphere ![image](https://user-images.githubusercontent.com/60821002/74967293-75680400-53f7-11ea-8b45-b656ed12fbcc.png)
the video here it s https://youtu.be/PFc-SMNBRmI i m wanting please

**Comment by adrian1978632** [comment]
@alex-w how make to fork and implement a model of atmosphere even editing files it work when you edit files and reload stellarium web

**Comment by adrian1978632** [comment]
@alex-w @guillaumechereau @cardinot https://youtu.be/AsBlW9WGXMA

**Comment by adrian1978632** [comment]
teach me how implementing a new model of atmosphere on stellarium web teach me please
