### ISSUE TITLE
Bottom buttons aren't visible on Chrome mobile

### ISSUE THREAD

**Issue by PawelPleskaczynski** [Stellarium/stellarium-web-engine#34]
Hello, I have an issue with Stellarium Web (it doesn't matter if it's served with `yarn run dev` or served statically with files built via `yarn run build` command), where buttons on the bottom of the screen are not visible. The buttons work on PCs, I tested on Windows and on Linux, on Firefox, Chromium and Edge, and they work everywhere. They just don't work on Chrome mobile, but they work on other mobile browsers, like Firefox mobile.

**Comment by xalioth** [comment]
I think this is fixed insce a while, please re-open if you can still reproduce
