### ISSUE TITLE
Search not working?

### ISSUE THREAD

**Issue by anzgar01** [Stellarium/stellarium-web-engine#35]
Hello,
first of all thanks a lot for this project, I really like it a lot.
After some issues (Linux noob) I got this up and running (at least the docker version), but for some reason the search doesn't work, as in it doesn't seem to be doing anything at all.
Any chance someone can point me in the right direction?

Is there actually a way to run this just using the javascript without the docker stuff from the /stellarium-web-enginge folder?
When running the "make js" there is no test-page.html in the html folder afterwards.
Thanks in advance!

**Comment by anzgar01** [comment]
Some more information:
after digging around and using firefox script console I found the following error which is probably causing the issues:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at URL https://api.noctuasky.com/api/v1/skysources/?q=RIGEL&limit=10
It seems that the CORS Header is missing from the webserver. As all of this runs inside a docker container, I have no clue how to fix this. 
Anybody here who can jump in with a short explanation please?

In addition to that: if I wanted to change the code (f.e. remove some GUI elements) and then recreate the docker container, where would I have to look?
Thanks a lot :-)

**Comment by xalioth** [comment]
Hi,

the CORS error is a security enforced in most modern browser letting a
website download JS/Json data only from servers explicitly allowing the
client service to do so.
Normally, if you run this on localhost it should work as I allowed our web
service to reply to those requests. Make sure to use http://localhost:8080
and not http://0.0.0.0:8080

For changing the GUI, just change the .vue files, the development server
should auto-reload it.

Fabien

**Comment by anzgar01** [comment]
Hi Fabien,
thanks for that fast reply!
It does indeed work if I use localhost instead of the IP, problem is I would like to use it on a webpage which will be accessed by IP/Hostname.
Any suggestions on how to get this done?
Ansgar

**Comment by xalioth** [comment]
Hi,

currently the web service used for doing object search is running on our
server so we don't want to let external program access it. The web server
code is also not open source (it contains a lot of sensitive information).
The best for you would be to develop a custom-made basic search feature to
replace the current one.

We unfortunately cannot add this in the engine because it's not possible to
do it on the client side, as it requires large data bases..

Fabien
