### ISSUE TITLE
There is no stellarium-web repo

### ISSUE THREAD

**Issue by ilsubyeega** [Stellarium/stellarium-web-engine#38]
[If you go stellarium-web](https://stellarium-web.org/) and About -> and [Github page](https://github.com/Stellarium/stellarium-web) is not exists. Is that repo private?

**Comment by xalioth** [comment]
The repo was merged with stellarium-web-engine. It's previous content is
now in the web-frontend folder.

Fabien

**Comment by ilsubyeega** [comment]
I think url should be changed

**Comment by xalioth** [comment]
You are right sorry and thanks. I'll fix that later today
