### ISSUE TITLE
Stellarium Web shows blank star map

### ISSUE THREAD

**Issue by ulricp** [Stellarium/stellarium-web-engine#40]
Stellarium Web version shows blank star field - please see attached screenshot.
I am using Google Chrome Version 80.0.3987.163 (Official Build) (64-bit).

All other parts of the page seem to work:
- I can toggle the left pane to hide it
- FOV angle changes when I scroll in or out
- All other page elements work (View Settings, Planets Tonight, Location selection etc)

![screencapture-stellarium-web-org-2020-04-15-14_11_50](https://user-images.githubusercontent.com/19305053/79341348-8d559300-7f23-11ea-9eab-c558b706ba5e.png)

**Comment by xalioth** [comment]
Hi,

could you display the JS console? You can bring the developer tool by doing
a right click / inspect, then go in the console tab. There you should see
some errors.

Fabien

**Comment by ulricp** [comment]
Here is the text of the error (also see attached screenshot of the console):

```
Uncaught TypeError: Cannot read property 'createTexture' of undefined
    at Zt (stellarium-web-engine.js:8)
    at en (stellarium-web-engine.js:8)
    at /wasm-function[1083]:0xa3441
    at Object.i._core_render (stellarium-web-engine.js:8)
    at t (stellarium-web-engine.js:8)
10A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
sw_helpers.js:459 GeoIP localization: {"lat":51.753,"lng":-0.3256,"accuracy":20000}
sw_helpers.js:494 Geocoding position...
2wasm://wasm/004596fe:1 Uncaught (in promise) RuntimeError: memory access out of bounds
    at wasm-function[323]:0x2b786
    at wasm-function[1111]:0xaf5b7
    at i._render_set_font (https://d3ufh70wg9uzo4.cloudfront.net/js/app.c9418e75.js:1:252166)
    at Object.H [as ccall] (https://d3ufh70wg9uzo4.cloudfront.net/js/app.c9418e75.js:1:202699)
    at https://d3ufh70wg9uzo4.cloudfront.net/js/app.c9418e75.js:1:190201
```

![2020-04-15 (2)](https://user-images.githubusercontent.com/19305053/79350092-ef67c580-7f2e-11ea-9083-4fab6409178d.png)

**Comment by xalioth** [comment]
Hi,

thanks, it's not so clear what the issue is here... Are you on windows?
Could you maybe try to full clean cache & reload. You can do that by
showing the inspector tool, and doing a right click on the reload page
button, it should show you: "Empty Cache & Hard reload".

Fabien

**Comment by ulricp** [comment]
Hi Fabien,
Fortunately the issue seems to have resolved itself. Just to be clear, I had this issue over several days over several reboots (yes its Windows 10) and now its gone. Thanks very much for your help anyway.

Ulric.
