### ISSUE TITLE
Add custom latitude/longitude in Stellarium Web application.

### ISSUE THREAD

**Issue by lnaceri000** [Stellarium/stellarium-web-engine#42]
I want to add custom latitude/longitude to Stellarium Web application.
I would like to manually enter latitude/longitude to Stellarium Web application.

**Comment by xalioth** [comment]
Currently you can do that by clicking on the map or alternatively by sepcifying lon and lat on the URL, like this:
https://stellarium-web.org?lat=43.49&lng=1.42

**Comment by lnaceri000** [comment]
![Uploading IMG_2011.png…]()

**Comment by lnaceri000** [comment]
![B5-F58-C19-6382-4-EB3-AFAB-0-D43-F54-CDE00](https://user-images.githubusercontent.com/64385642/81728344-e8f63c00-944f-11ea-99bb-86ce6e33d55d.png)

**Comment by lulunac27a** [comment]
I still can't set the custom latitude and longitude if that place is in the ocean like [this](https://stellarium-web.org/?lat=1&lng=1), this app should add a text input for setting the latitude and longitude values.
