### ISSUE TITLE
Date/time control buttons (up and down) not working on Chrome/Android and on Chrome/Windows/touchScreen

### ISSUE THREAD

**Issue by fabriciodosanjossilva** [Stellarium/stellarium-web-engine#43]
Date/time control buttons (up/add and down/subtract) not working on Chrome/Android and Chrome/Windows/touchScreen. They get highlighted, but do not respond. It should be noted that on Chrome/Windows, if the buttons are clicked, it works fine. But not if touched. On Chrome/Android, this issue severely blocks user from altering date/time.

**Comment by lnaceri000** [comment]
I get this same issue too!

**Comment by retroj** [comment]
I see this issue as well on both Android and iOS (Safari).

**Comment by dccoloso** [comment]
Same here. Not working in serveral Android devices I tried it on.
Android 5, 7 and 9. Android browsers Chrome, Safari and stock Redmi
Also tried it on Bluestacks.

**Comment by xalioth** [comment]
Fixed in e92a8481
