### ISSUE TITLE
"Couldnt find skysource" information for some stars

### ISSUE THREAD

**Issue by BradleyPelton** [Stellarium/stellarium-web-engine#50]
DISCLAIMER: I havent seen this before, it might not be a bug. Feel free to close the issue if it isnt.

### Summary
TLDR: https://gyazo.com/656e7a16a1b5ac20dec4feb7d3b96b91
SUMMARY: A cluster of stars all are not displaying their "v-sheet"/basic information panel. 
PRIORITY: Medium

### STAR NAMES:
- C/2019 Y4-A (Atlas)
- C/2019 Y4-B (Atlas)
- C/2019 Y4-C (Atlas)

### Expected Behavior
The "v-sheet"/informational panel should display for all clickable objects

### Actual Behavior
The panel doesnt display for these specific stars

Gif of execution
https://gyazo.com/656e7a16a1b5ac20dec4feb7d3b96b91

**Comment by gzotti** [comment]
These names clearly label not stars, but the fragments of comet C/2019 Y4 (Atlas).

**Comment by BradleyPelton** [comment]
I must have missed it, where did you see it labeled?

**Comment by gzotti** [comment]
These designations are for comets. I don't need a computer program to say this.

**Comment by xalioth** [comment]
Solved in last release!
