### ISSUE TITLE
Camera FOV Rectangle possible?

### ISSUE THREAD

**Issue by thomome** [Stellarium/stellarium-web-engine#54]
I am currently trying to add a fov of a camera ([like in the desktop version of Stellarium](https://imgur.com/2exaPeP)). The function `stel.createObj('circle', {...})` allows me to do exactly that but in the shape of a circle or ellipse. Is there a way to add an rectangle instead?

**Comment by guillaumechereau** [comment]
It used to be possible to do the same with "rectangle" instead of "circle".  However currently the recommended way is to use the geojson support to add any shape you want.  You can have a look in the html/debug-page.hml to see how to add geojson shape in the sky.

**Comment by thomome** [comment]
Thanks. That worked fine.
