### ISSUE TITLE
Feature - share/bookmark current view

### ISSUE THREAD

**Issue by orionlee** [Stellarium/stellarium-web-engine#60]
It'd be great if stellarium web let users book / share current view.

I imagine it could be something like this:
https://stellarium-web.org/#<identifiers encoded the view's current location, direction, view settings, etc.)

The engine, upon seeing such identifiers, will adjust the map accordingly.

**Comment by xalioth** [comment]
Hi Sam,

if you select and center an object you can copy a link to the current view
in the object informations.

For example https://stellarium-web.org/skysource/M
106?fov=1.4864&date=2020-08-01T20:49:28Z&lat=48.30&lng=10.86&elev=0
You can also just add the fov, date etc.. parameters to the base URL to
create views.

Hope it helps!

Fabien

**Comment by orionlee** [comment]
Hi Fabien,

Thanks! I never clicked the center object icon, and didn't realize there was a copy link available.

**Comment by ralienpp** [comment]
I came here looking for the same thing, and even though I learned the feature is there - it took a while to find it. For the benefit of others, here's what to look for:

![image](https://user-images.githubusercontent.com/295338/221559942-4f4284d3-e27b-4322-b675-46ce5cb79f58.png)

![image](https://user-images.githubusercontent.com/295338/221560000-1ee007c0-dca5-404d-9018-f1c898ee3ca5.png)


To sum things up:
1. click on the object of interest
2. click the white round icon that looks like a crosshair
3. and then the "get link" icon is shown


I believe that in terms of usability, the discoverability of this feature could be improved. For example, if you put it in the toolbar, most users would probably figure it out quickly:

![image](https://user-images.githubusercontent.com/295338/221561134-8d16ee96-f3dd-443b-ab48-ca7c6aaf30b4.png)




Background info - I rely on Stellarium to ensure I have accurate depictions of the night sky in the illustrations of a children's poetry book I'm working on. I visited the site quite often over the past few weeks, and each time I went through multiple steps to go to "the same place". Even as a very motivated user, I didn't stumble upon this feature, despite having spent a relatively long time in the UI.

**Comment by claudemartin** [comment]
I was looking for this and it's so hard to find. Even with the information given by ralienpp it wasn't easy. This whould be a lot simpler to find. Why would you even have to click a crosshair symbol for that? Why isn't the link symbol available at all times?
