### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application:

### ISSUE THREAD

**Issue by mfurqanliaqat** [Stellarium/stellarium-web-engine#63]
Hey There, Devs!
I am having an issue while building stellarium-web-engine.js and stellarium-web-engine.wasm.
everything works fine, untill setting up path using emscripten,
when i execute

> make js

I am getting an error as : 

`C:\Users\M. FURQAN LIAQAT\Desktop\stellarium-web-engine-master>make js`
`make i info Invoking js target`
`OSError: [WinError 193] %1 is not a valid Win32 application:`
`File "C:\Users\M. FURQAN LIAQAT\Desktop\stellarium-web-engine-master\SConstruct", line 185:`
` call('./tools/make-assets.py')`
 `File "c:\users\m. furqan liaqat\appdata\local\programs\python\python38\lib\subprocess.py", line 340:`
 `   with Popen(*popenargs, **kwargs) as p:`
 ` File "c:\users\m. furqan liaqat\appdata\local\programs\python\python38\lib\subprocess.py", line 854:`
 `   self._execute_child(args, executable, preexec_fn, close_fds,`
`  File "c:\users\m. furqan liaqat\appdata\local\programs\python\python38\lib\subprocess.py", line 1307:`
 `   hp, ht, pid, tid = _winapi.CreateProcess(executable, args,`
`make × ERR  emscons scons -j8 mode=release`
`make × ERR  Recipe exited with code %d`
`(node:10692) UnhandledPromiseRejectionWarning: Error: Recipe exited with code %d`
   ` at ChildProcess.<anonymous> (C:\Users\M. FURQAN LIAQAT\AppData\Roaming\npm\node_modules\make\src\cli.js:143:28)`
    `at ChildProcess.emit (events.js:315:20)`
    `at maybeClose (internal/child_process.js:1021:16)`
    `at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)`
`(node:10692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I have tried a couple of fixes, doesn't work at all.
I have  both emscripten and sconstruct installed. also ENVIRONMENT VARIABLES are set.

I am on WIndows 10 Pro
Python 3.8 x64

I think there can be a version missmatch or something like this, any help would be valuable:)
Regards!
Thanks in advance:)

**Comment by xalioth** [comment]
Hi, please try to do the following to bootstrap the build:

make setup
make dev

I am really unsure about building everything on windows. We use a linux
ubuntu to build, even when using docker, at least the "make" utility must
be functional.

Fabien

**Comment by honwenle** [comment]
I got the totally same quetion.
I guess that it because emsdk has its own python and i have another.
When i run `source ./emsdk_env.sh` it output python_path which in the emsdk.
I installed the `scons` by pip which in my PC.
But i still don't know how can fixed it, so i need help!
