### ISSUE TITLE
the algorithm of dso's interest?

### ISSUE THREAD

**Issue by ultrapre** [Stellarium/stellarium-web-engine#64]
The api request of `https://api.noctuasky.com/api/v1/skysources/` will return such a list, and they seem to be sorted by "interest". How to calculate objects' "interest" info ?

```
[{"interest":4.6296,"match":"NGC 6231","model":"dso",…
```

**Comment by xalioth** [comment]
Hi,

it's a mixture of magnitude/size and catalog importance. E.g. a Messier object will normally have a higher interest than an NGC, which itself will have a higher ranking as a PGC  etc..

The algorithm is not very evolved and is not very correct yet, and ideally we would need something more community-based, or based on google search queries to get a better popularity index.
