### ISSUE TITLE
default time

### ISSUE THREAD

**Issue by anzgar01** [Stellarium/stellarium-web-engine#65]
Sorry if this is not the right place for this question:

Is there a way to set a default time (and location) for each user to access the site?
I found a similar question on sourceforge with no answer so far.

On android it looks like something similar is implemented, because it always shows the sky at nighttime. On desktop (windows) however it uses the actual time.

Is there an easy way to do this? Or mayber a difficult one by changing the source code?

Thanks in advance!

**Comment by xalioth** [comment]
This is not really possible to implement that unless users are logged-in with saved preferences..

**Comment by anzgar01** [comment]
Actually what I was aiming for was setting a default time that is used for each user.
So one default time for everyone, and not the ability for each user to set his own.

Somehow I think this is working now, so that might have been some misconfiguration in my browser, because it now skips to 9pm after loading, which is fine for me.
@xalioth not sure if I should close the issue myself, but you can close it if you like.

**Comment by anzgar01** [comment]
As there was no further comment and the issue was solved I will close the issue

**Comment by xalioth** [comment]
Thanks, sorry I missed the previous messages!
