### ISSUE TITLE
Changing date and time - it seems that does - right now - not work in Google Chrome but e.g. in Safari

### ISSUE THREAD

**Issue by waehringer** [Stellarium/stellarium-web-engine#67]

**Comment by xalioth** [comment]
Other feedback from Maria:

"Sometimes, when I use the Stellarium Web I can't change the clock (months, yeras, hours... I can't change anything with the arrows). 
I wondered if you know how I can solve this problem."

**Comment by xalioth** [comment]
Fixed in e92a8481, release coming soon
