### ISSUE TITLE
Error in Pluto's position relative to background stars?

### ISSUE THREAD

**Issue by gammaxy1** [Stellarium/stellarium-web-engine#69]
At https://stellarium-web.org/, I noticed the position of Pluto appears to be wrong against the background stars.  The RA shows 19h 38m38.4s, but theskylive.com shows 19h 36m41.0s.  The Stellarium software on my PC shows it at the same location as theskylive.com and I believe I see it at that location through my telescope.

If this is a real issue, I suspect it affects the other planets since I see differences in their RA as well, but interestingly not the exact same amount.

**Comment by xalioth** [comment]
I can't reproduce on the last release. I close, please re-open if you can still reproduce
