### ISSUE TITLE
Stellarium-Web.org constellation toggle currently only shows constellations near center of view

### ISSUE THREAD

**Issue by asymptotic-giant** [Stellarium/stellarium-web-engine#71]
Very recently the constellation toggle would show ALL constellations, now it is only showing those near the center of view. 

I have students using this as a resource in distance learning and it's making it difficult for them.

**Comment by xalioth** [comment]
Hello,

thanks for reporting, this is a regression which slipped into today's release. I just pushed a fix, and I'll deploy it very soon.

Fabien

**Comment by swaterfall** [comment]
This seems to happening again?
<img width="1507" alt="Screenshot 2021-11-05 at 17 31 08" src="https://user-images.githubusercontent.com/541538/140553735-df262fbf-f356-4fc1-97d8-741f04a705b8.png">

**Comment by xalioth** [comment]
On the online version everything seems OK.
