### ISSUE TITLE
RFC - stellarium for ancient time (B.C.)

### ISSUE THREAD

**Issue by WebSimConnect** [Stellarium/stellarium-web-engine#72]
Hi,

I wanted to use https://stellarium-web.org/ to verify some sky picture from ancient time. Unfortunatelly your program does not accept years B.C, e.g. <0 and navigates back to 1858. Would it be possible to unblock BC years ?

**Comment by gzotti** [comment]
This may not be a matter of "unblocking" but of deliberately limiting the range of accessible data so that the model behaves well.
The classical Stellarium desktop program may be better suited for historical questions.

**Comment by WebSimConnect** [comment]
Indeed, I used desktop version and was able to navigate through ancient times. Thx.
