### ISSUE TITLE
Search no longer working on android

### ISSUE THREAD

**Issue by anzgar01** [Stellarium/stellarium-web-engine#75]
I just found out that the search function is no longer working on at least 2 android devices I tested (tested both local and with stellarium-web.org).
F.e. if I search for "Capella" or anything else using the search field, I do get the list with suggestions as usual. But whenever I click on one of the results, nothing happens (the selected-object-info does not show, and the screen does not center on the selected star).

Is there a fix for this?

Thanks in advance!

**Comment by xalioth** [comment]
I can reproduce on my phone as well, but I have very limited time right now, I'll check that in a few days.

**Comment by anzgar01** [comment]
Great, thanks in advance. I would try to find it myself but wouldn't even know where to start looking :-)

**Comment by xalioth** [comment]
Fixed in dc60220b, release coming soon
