### ISSUE TITLE
Where is "stellarium-web-engine.js"?

### ISSUE THREAD

**Issue by lexterror** [Stellarium/stellarium-web-engine#8]
Could you please send me the link for "stellarium-web-engine.js"

Thank you

**Comment by xalioth** [comment]
You need to use the stellarium-web branch of this repo, and check in the web-frontend directory on build instructions.

**Comment by binoysarker** [comment]
there is no stellarium-web-engine.js and stellarium-web-engine.wasm file in assets directory and it is asking for this when i run npm run dev in web-frontend directory.

**Comment by xalioth** [comment]
Hi,
thanks I update the README file to add missing instructions to generate the stellarium-web-engine.js and stellarium-web-engine.wasm files.
Fabien
