### ISSUE TITLE
Setup Failing For Docker

### ISSUE THREAD

**Issue by shrhawk-entertainer** [Stellarium/stellarium-web-engine#82]
While trying to set up the project locally using docker following command fails

`make setup`

# Build docker image for compilation with emscripten
docker build -f Dockerfile.jsbuild -t swe-dev . # --no-cache
[+] Building 2.8s (8/8) FINISHED
 => [internal] load build definition from Dockerfile.jsbuild                                                                                                                                               0.0s
 => => transferring dockerfile: 45B                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/emscripten/emsdk:1.39.17                                                                                                                                        2.7s
 => [auth] emscripten/emsdk:pull token for registry-1.docker.io                                                                                                                                            0.0s
 => [1/3] FROM docker.io/emscripten/emsdk:1.39.17@sha256:1e264934c11ffde8511441eaed6bdc44eaa30ec027e46d38be7ae67106aefdab                                                                                  0.0s
 => CACHED [2/3] RUN apt-get update && apt-get install -y wget build-essential apt-transport-https scons                                                                                                   0.0s
 => CACHED [3/3] WORKDIR /app                                                                                                                                                                              0.0s
 => exporting to image                                                                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                                                                    0.0s
 => => writing image sha256:bffb53175a1021f8b35cbc0af0a32ae6d4c2751a9716173ded1b7ddf922ff62c                                                                                                               0.0s
 => => naming to docker.io/library/swe-dev                                                                                                                                                                 0.0s
make update-engine
make gen-es6
cd .. && docker run -it -p 8000:8000 -v "/Users/shrhawk/stellarium-web-engine/web-frontend/..:/app" swe-dev /bin/bash -c "source /emsdk/emsdk_env.sh && make js-es6"
Setting environment variables:
EMSDK = /emsdk
EM_CACHE = /emsdk/upstream/emscripten/cache

emscons scons -j8 mode=release es6=1
cache:INFO: generating system asset: is_vanilla.txt... (this will be cached in "/emsdk/upstream/emscripten/cache/is_vanilla.txt" for subsequent builds)
cache:INFO:  - ok
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: *** [SConstruct] ValueError : unsupported pickle protocol: 4
scons: building terminated because of errors.
make: *** [Makefile:18: js-es6] Error 2
make[2]: *** [gen-es6] Error 2
make[1]: *** [update-engine] Error 2
make: *** [setup] Error 2

**Comment by xalioth** [comment]
It looks like to have remanent stuff from an older python version that you tried to run without docker.
Please clean the web-frontend directory of any python temporary files and try again.

**Comment by luk0y** [comment]
@shrhawk-entertainer Try this https://github.com/Stellarium/stellarium-web-engine/issues/168#issuecomment-1343799586. It worked for me.
