### ISSUE TITLE
Possible CORS issues when retrieving data on a object

### ISSUE THREAD

**Issue by stephenguerin** [Stellarium/stellarium-web-engine#85]
three days ago I noticed I was unable to get the star info panel to display reliably. Console eventually shows a CORS issue:

![image](https://user-images.githubusercontent.com/1078567/113379769-a2dfea80-9337-11eb-8e20-fa932d8971d0.png)

After 10-20 seconds it does seem to catch up with data but doesn't update the star name in the info panel. If it helps, I also get these animation frame warnings:
![image](https://user-images.githubusercontent.com/1078567/113379892-036f2780-9338-11eb-8844-7b9f55ecb03c.png)

**Comment by xalioth** [comment]
Hi, there was an issue on one of our webservice. Not clear what the problem was but a reboot seems to fix the issue.. Please confirm and close issue!

Thanks for the report!

**Comment by stephenguerin** [comment]
Fabian,

Thanks, confirmed and will close.

A simple browser fresh wasn't working yesterday. Though "empty cache and hard reload" did work. CORS issues in console are also gone.

for others,  "Empty cache and hard reload" is only available as a right-click on refresh while dev tools is open
![image](https://user-images.githubusercontent.com/1078567/113434509-554a9880-939e-11eb-845a-6662662b379b.png)
