### ISSUE TITLE
Unable to create account in stellarium-web

### ISSUE THREAD

**Issue by Abelink23** [Stellarium/stellarium-web-engine#9]
When I try to create an account on https://stellarium-web.org/p/users/signup (cookies and everything es enabled), I get this message all the time: "Cannot read property 'body' of undefined".
Therefore I have not been able to create it. 

Many thanks.

**Comment by xalioth** [comment]
Indeed I can reproduce that. I'll fix that ASAP..

**Comment by xalioth** [comment]
OK, it was ultimately an SMTP server issue.. Fixed, thanks for the report!
